# Generated by Django 2.2.9 on 2020-02-07 15:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='blank',
            fields=[
                ('number', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('444', 'international up to four coupons'), ('440', 'manual - international'), ('420', 'international with two coupons'), ('201', 'domestic with two coupons'), ('101', 'domestic with one coupon'), ('451', 'MCO'), ('452', 'MCO')], default='green', max_length=50)),
                ('is_sold', models.BooleanField(default=False)),
                ('is_refunded', models.BooleanField(default=False)),
                ('advisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
